name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Artifact
        run: |
          mkdir -p public
          cp luxverify-embed.html public/
          cp model.json public/
          cp weights.bin public/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public
          retention-days: 1
          if-no-files-found: error  # Fail if no files
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pagesHUB_TOKEN }}
          artifact_name: github-pages
